name: snp_shared
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.16.1"

dependencies:
  http: ^0.13.4
  encrypt: ^5.0.1
  equatable:
  dio:
  uuid:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
