name: snp_test
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  snp_shared:
    path: "../snp-shared"
  snp_client:
    path: "../snp-client"
  snp_server:
    path: "../snp-server"
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
