name: snp_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.16.1"


dependencies:
  logging:
  http: ^0.13.4
  mockito:
  snp_shared:
    path: '../snp-shared'
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
