name: snp_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.0-16.0.dev <3.0.0'


dependencies:
  logging:
  snp_shared:
    path: '../snp-shared'
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
